version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/elearning-monolith.jar
  discard-paths: yes